id: I2285128F
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:28:57.594168
last_modified: 2023-01-04 11:28:57.594180
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  '9317':
    title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of Do
      Khyentsé Yeshé Dorjé
    base_file: 9317.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
